robot_handler.set_motors_velocity(7, 7)
robot_handler.wait_for(2)
# Third Sphere
# Around the third sphere from the right side
robot_handler.set_motors_velocity(5, 2)
robot_handler.wait_for(1)
robot_handler.set_motors_velocity(4, 5)
robot_handler.wait_for(3)
robot_handler.set_motors_velocity(3, 5)
robot_handler.wait_for(4)
# Fourth Sphere
robot_handler.set_motors_velocity(5, 3)
robot_handler.wait_for(4)
robot_handler.set_motors_velocity(5, 4)
robot_handler.wait_for(2)
robot_handler.set_motors_velocity(5, 3)
robot_handler.wait_for(5)
# Go to the opposite site
robot_handler.set_motors_velocity(5, 4.5)
robot_handler.wait_for(7)
robot_handler.set_motors_velocity(5, 3.9)
robot_handler.wait_for(5)
robot_handler.set_motors_velocity(5, 3)
robot_handler.wait_for(3)
robot_handler.set_motors_velocity(5, 4)
robot_handler.wait_for(6)
robot_handler.set_motors_velocity(4, 5)
robot_handler.wait_for(3)
robot_handler.set_motors_velocity(3, 5)
robot_handler.wait_for(3)
robot_handler.set_motors_velocity(5, 3)
robot_handler.wait_for(3)
robot_handler.set_motors_velocity(5, 4)
robot_handler.wait_for(3)
robot_handler.set_motors_velocity(4, 5)
robot_handler.wait_for(3)
robot_handler.set_motors_velocity(3, 5)
robot_handler.wait_for(1)
robot_handler.set_motors_velocity(4.5, 5)
robot_handler.wait_for(2)
robot_handler.set_motors_velocity(5, 5)
robot_handler.wait_for(4)